# Generated by Django 5.0.6 on 2024-07-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
