# Generated by Django 5.0.6 on 2024-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_published_quiz_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
