# Generated by Django 5.0.6 on 2024-07-07 11:13

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 7, 7, 11, 13, 7, 203314, tzinfo=datetime.timezone.utc))]),
        ),
    ]
