# Generated by Django 5.0.6 on 2024-07-07 11:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 7, 7, 11, 13, 39, 797021, tzinfo=datetime.timezone.utc))]),
        ),
    ]
