# Generated by Django 5.0.6 on 2024-07-07 13:02

import datetime
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 7, 7, 13, 2, 23, 221828, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterUniqueTogether(
            name='userquiz',
            unique_together={('user', 'quiz')},
        ),
    ]
