# Generated by Django 5.0.6 on 2024-07-07 14:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quiz_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='userquiz',
            options={'verbose_name': 'User Quiz', 'verbose_name_plural': 'User Quizzes'},
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 7, 7, 14, 11, 1, 348248, tzinfo=datetime.timezone.utc))]),
        ),
    ]
