# Generated by Django 5.0.6 on 2024-07-07 14:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quiz_options_alter_userquiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 7, 7, 14, 11, 6, 30994, tzinfo=datetime.timezone.utc))]),
        ),
    ]
