# Generated by Django 5.0.6 on 2024-07-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_quiz_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoptions',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
