# Generated by Django 5.0.6 on 2024-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_questionoptions_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
