# Generated by Django 5.0.6 on 2024-07-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_question_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuestionAns',
            new_name='UserQuestionAnswer',
        ),
        migrations.RenameField(
            model_name='userquestionanswer',
            old_name='ans',
            new_name='answer',
        ),
        migrations.AlterUniqueTogether(
            name='userquestionanswer',
            unique_together={('user_quiz', 'question', 'answer')},
        ),
    ]
