# Generated by Django 5.0.6 on 2024-07-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_rename_userquestionans_userquestionanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questionoptions'),
        ),
    ]
