# Generated by Django 5.1.1 on 2024-10-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_remove_level_quizzes_level_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.level'),
        ),
    ]
