# Generated by Django 5.1.1 on 2024-10-02 10:34
from django.db import migrations, models
from django.db import migrations
from django.utils.text import slugify

def generate_unique_slugs(apps, schema_editor):
    Level = apps.get_model('quiz', 'Level')
    for level in Level.objects.all():
        # Generate a unique slug based on the level name
        level.slug = slugify(level.name)
        
        # Save the level with the new slug
        level.save()

class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_quiz_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='slug',
            field=models.SlugField(unique=True, blank=True, null=True),
        ),
        migrations.RunPython(generate_unique_slugs),
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
