# Generated by Django 5.0.6 on 2024-10-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_level_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
    ]
