# Generated by Django 5.0.6 on 2024-10-12 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_reward_userpoints_userreward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPoints',
            new_name='UserPoint',
        ),
    ]
