# Generated by Django 5.0.6 on 2024-10-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_rename_userpoint_userscore_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquiz',
            old_name='time_left',
            new_name='play_time',
        ),
        migrations.RemoveField(
            model_name='userquiz',
            name='is_score_added',
        ),
        migrations.AddField(
            model_name='userquiz',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
