# Generated by Django 5.0.6 on 2024-10-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_rename_time_left_userquiz_play_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='is_score_added_total',
            field=models.BooleanField(default=False),
        ),
    ]
