# Generated by Django 5.0.6 on 2024-10-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_userquiz_is_score_added_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='is_time_added_total',
            field=models.BooleanField(default=False),
        ),
    ]
