# Generated by Django 5.0.6 on 2024-10-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_remove_userquiz_is_time_added_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='full_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='is_time_added_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
