# Generated by Django 5.0.6 on 2024-10-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_userquiz_end_time_userquiz_full_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='total_time',
            field=models.FloatField(default=0),
        ),
    ]
