# Generated by Django 5.0.6 on 2024-10-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_userscore_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='is_time_added_total',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='total_time',
        ),
        migrations.AddField(
            model_name='userquiz',
            name='calculated_score',
            field=models.IntegerField(default=0),
        ),
    ]
