# Generated by Django 5.0.6 on 2024-10-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_remove_userquiz_is_time_added_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='exchanged_points',
            field=models.IntegerField(default=0),
        ),
    ]
